public class FBE_FPRM_DealConstants {
    public final static String[] FILTERS = new String[]{'%APOS%','%Nutanix%','%XC Series%', '%Service%','%SonicWALL%', '%VMWare%', '%Maintenance%', '%Warranty Extension%', '%Warranty%', '%Entitlement%', '%Renewal%'};   
    public final static Set<String> CSG_BU_CATEGORIES = new Set<String>{'CSG Hardware', 'CSG Other'};
    public final static List<String> distiVARAccTeamRoles = new List<String>{'AE','SR'};
    public final static String[] APOS_FILTERS = new String[]{'%APOS%','%Service%',  '%Maintenance%', '%Warranty Extension%', '%Warranty%', '%Entitlement%', '%Renewal%'};
}