/**************
*@ Class Name                                                    : FBE_ConfiguratorHandler
*@ Description                                                   : This class is to maintain test methods for all configurator logics.
*@ CreatedBy                                                     : Dell Team
*@ CreatedOn                                                     : 04-01-2020 [Lavakumar Tonupunuri]
*@ Modification Log                                              : 
***************/ 
public class FBE_ConfiguratorHandlerTest {

}